### ISSUE TITLE
Can't stop Raft.

### ISSUE THREAD

**Issue by sunli829** [async-raft/async-raft#79]
Thank you for the great library, but I found a problem. After I call `Raft::shutdown`, Raft cannot stop and keep outputting the following message.

```
async_raft::core error reporting metrics error=channel closed id=1 
async_raft::core error reporting metrics error=channel closed id=1 
async_raft::core error reporting metrics error=channel closed id=2 
async_raft::core error reporting metrics error=channel closed id=0 
async_raft::core error reporting metrics error=channel closed id=2 
async_raft::core error reporting metrics error=channel closed id=0 
```

**Comment by thedodd** [comment]
@sunli829 very interesting, thanks for the report! I wonder if this is just a matter of the metrics system being kept alive due to a receiver being alive somewhere. I will look into this.

**Comment by thedodd** [comment]
@sunli829 a few follow-up questions:
- are you awaiting the JoinHandle returned from `raft.shutdown()`?
- not that I'm sure this would cause a problem, but do you have any additional `watch::Receiver<RaftMetrics>` handles being retained anywhere? This shouldn't cause problems, but just in the name of gathering data, I figured I would ask.
- any other pertinent info on your setup?

**Comment by thedodd** [comment]
Based on a quick review of master (corresponding to 0.5.1), the shutdown routine seems to be correct ... I will need more information to be able to pin down what might be causing this behavior in your system.

**Comment by thedodd** [comment]
@sunli829 ok, I believe I found the issue. Will get a bug fix released pretty quickly.

**Comment by thedodd** [comment]
`v0.5.2` will be released shortly! Thanks again for the bug report @sunli829!

**Comment by sunli829** [comment]
Thank you for your quick response.
But I still can't stop it, I modified a test case to reproduce it.😁

repo: https://github.com/sunli829/async-raft.git
branch: metrics-serialize

https://github.com/sunli829/async-raft/blob/8a48f709599372f96b7ea99609ff48cbde94e0a3/async-raft/tests/initialization.rs#L25

**Comment by thedodd** [comment]
@sunli829 you are absolutely correct. I apologize for the false-positive. I have added a new test to the integration test suite, updated the core code with an "actual" fix `:)`, and will have a release out for that shortly.
